# Generated by Django 5.0.4 on 2024-05-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock_level_threshold',
        ),
    ]
