# Generated by Django 5.0.4 on 2024-05-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0005_navbarcustomization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbarcustomization',
            name='text_color',
        ),
        migrations.RemoveField(
            model_name='navbarcustomization',
            name='user',
        ),
        migrations.AddField(
            model_name='navbarcustomization',
            name='button_text_color',
            field=models.CharField(default='White', max_length=20),
        ),
        migrations.AddField(
            model_name='navbarcustomization',
            name='company_text_color',
            field=models.CharField(default='White', max_length=20),
        ),
        migrations.AlterField(
            model_name='navbarcustomization',
            name='background_color',
            field=models.CharField(default='Blue', max_length=20),
        ),
    ]
