# Generated by Django 5.0.4 on 2024-05-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0006_remove_navbarcustomization_text_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='White', max_length=20)),
                ('box_color', models.CharField(default='white', max_length=20)),
                ('title_text_color', models.CharField(default='Black', max_length=20)),
                ('input_text_color', models.CharField(default='Black', max_length=20)),
                ('button_color', models.CharField(default='Green', max_length=20)),
            ],
        ),
    ]
