# Generated by Django 5.0.4 on 2024-05-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0008_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('PLACE_ORDER', 'Place Order'), ('TO_PROCESS', 'To Process'), ('TO_SHIP', 'To Ship'), ('TO_DELIVER', 'To Deliver'), ('DELIVERED', 'Delivered'), ('CANCEL_ORDER', 'Cancel Order')], max_length=20, null=True),
        ),
    ]
