# Generated by Django 5.0.4 on 2024-05-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0010_purchaseorder_category_purchaseorder_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='White', max_length=20)),
                ('box_color', models.CharField(default='white', max_length=20)),
                ('title_text_color', models.CharField(default='Black', max_length=20)),
                ('other_text_color', models.CharField(default='Black', max_length=20)),
                ('table_header_color', models.CharField(default='#f4f4f4', max_length=20)),
                ('table_row_color', models.CharField(default='#fff', max_length=20)),
            ],
        ),
    ]
