# Generated by Django 5.0.4 on 2024-05-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0011_mainpagecustomization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpagecustomization',
            old_name='other_text_color',
            new_name='table_header_text_color',
        ),
        migrations.AddField(
            model_name='mainpagecustomization',
            name='table_text_color',
            field=models.CharField(default='Black', max_length=20),
        ),
    ]
