# Generated by Django 5.0.4 on 2024-06-05 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0014_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='None', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_in_stock', models.IntegerField()),
                ('unit_of_measurement', models.CharField(max_length=50)),
                ('reorder_level', models.IntegerField()),
                ('supplier', models.ForeignKey(limit_choices_to={'is_supplier': True}, on_delete=django.db.models.deletion.CASCADE, to='inventoryapp.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Baked',
        ),
        migrations.DeleteModel(
            name='Beverages',
        ),
        migrations.DeleteModel(
            name='Condiments',
        ),
        migrations.DeleteModel(
            name='Dairy',
        ),
        migrations.DeleteModel(
            name='Dry',
        ),
        migrations.DeleteModel(
            name='Meats',
        ),
        migrations.DeleteModel(
            name='Packaging',
        ),
        migrations.DeleteModel(
            name='Plants',
        ),
    ]
