# Generated by Django 5.0.4 on 2024-06-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0015_products_delete_baked_delete_beverages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_status',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accept'), ('REJECTED', 'Reject')], default='Pending', max_length=20, null=True),
        ),
    ]
